# Generated by Django 3.0.5 on 2020-04-13 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='department', chained_model_field='department', null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Position'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Province'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='site',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='province', chained_model_field='province', null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Site'),
        ),
    ]
