# Generated by Django 3.0.5 on 2020-04-15 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20200415_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='user',
        ),
    ]
