# Generated by Django 3.0.5 on 2020-04-21 10:20

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20200415_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='department', chained_model_field='department', default=1, on_delete=django.db.models.deletion.CASCADE, to='employees.Position'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='site',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='province', chained_model_field='province', default=1, on_delete=django.db.models.deletion.CASCADE, to='employees.Site'),
            preserve_default=False,
        ),
    ]
