# Generated by Django 3.0.5 on 2020-05-03 12:34

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_auto_20200430_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to='employees.Department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='department', chained_model_field='department', default=10, on_delete=django.db.models.deletion.CASCADE, to='employees.Position'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='province',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, to='employees.Province'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='site',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='province', chained_model_field='province', default=6, on_delete=django.db.models.deletion.CASCADE, to='employees.Site'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, default=9, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.Department'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='position',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='department', chained_model_field='department', db_constraint=False, default=10, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.Position'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='province',
            field=models.ForeignKey(blank=True, db_constraint=False, default=7, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.Province'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='site',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='province', chained_model_field='province', db_constraint=False, default=6, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.Site'),
        ),
    ]
