# Generated by Django 3.0.5 on 2020-05-03 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_auto_20200503_1707'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalEmployee',
        ),
    ]
