# Generated by Django 3.0.5 on 2020-05-10 11:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0014_auto_20200510_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Invalid Afghanistan Phone number', regex='[0][7][024789][0-9]{7}')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='skype',
            field=models.CharField(blank=True, max_length=31, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_skype_id', message='Invalid Skype ID', regex='[a-zA-Z][a-zA-Z0-9\\.,\\-_]{5,31}')]),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='phonenumber',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Invalid Afghanistan Phone number', regex='[0][7][024789][0-9]{7}')]),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='skype',
            field=models.CharField(blank=True, db_index=True, max_length=31, null=True, validators=[django.core.validators.RegexValidator(code='invalid_skype_id', message='Invalid Skype ID', regex='[a-zA-Z][a-zA-Z0-9\\.,\\-_]{5,31}')]),
        ),
        migrations.CreateModel(
            name='IPPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension_number', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_extension_number', message='Invalid Extension number', regex='[6][0-4][0-9]')])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Department')),
                ('employees', models.ManyToManyField(to='employees.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalIPPhoneNumber',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('extension_number', models.CharField(db_index=True, max_length=3, validators=[django.core.validators.RegexValidator(code='invalid_extension_number', message='Invalid Extension number', regex='[6][0-4][0-9]')])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.Department')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical ip phone number',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
