# Generated by Django 3.0.5 on 2020-05-10 11:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0015_auto_20200510_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(max_length=255)),
                ('extension_number', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_extension_number', message='Invalid Extension number', regex='[6][0-4][0-9]')])),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalExtensionNumber',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('office', models.CharField(max_length=255)),
                ('extension_number', models.CharField(db_index=True, max_length=3, validators=[django.core.validators.RegexValidator(code='invalid_extension_number', message='Invalid Extension number', regex='[6][0-4][0-9]')])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical extension number',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name='ipphonenumber',
            name='department',
        ),
        migrations.RemoveField(
            model_name='ipphonenumber',
            name='employees',
        ),
        migrations.DeleteModel(
            name='HistoricalIPPhoneNumber',
        ),
        migrations.DeleteModel(
            name='IPPhoneNumber',
        ),
    ]
