# Generated by Django 3.0.5 on 2020-05-11 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_auto_20200510_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Invalid Afghanistan Phone number', regex='[0][7][02346789][0-9]{7}')]),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='phonenumber',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Invalid Afghanistan Phone number', regex='[0][7][02346789][0-9]{7}')]),
        ),
    ]
