# Generated by Django 3.0.5 on 2020-07-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_auto_20200511_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalextensionnumber',
            name='department',
        ),
        migrations.RemoveField(
            model_name='historicalextensionnumber',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='skype',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='skype',
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End of contract'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End of contract'),
        ),
        migrations.DeleteModel(
            name='ExtensionNumber',
        ),
        migrations.DeleteModel(
            name='HistoricalExtensionNumber',
        ),
    ]
