# Generated by Django 3.0.5 on 2020-04-15 15:08

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='category',
        ),
        migrations.AddField(
            model_name='model',
            name='category',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='manufacturer', chained_model_field='manufacturers', default=0, on_delete=django.db.models.deletion.CASCADE, to='items.Category'),
            preserve_default=False,
        ),
    ]
