# Generated by Django 3.0.5 on 2020-04-15 15:51

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20200415_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='model',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='manufacturer', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='items.Model'),
        ),
    ]
