# Generated by Django 3.0.5 on 2020-04-26 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20200423_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='serial',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='tag_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='SpecInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.SpecList')),
            ],
        ),
    ]
