# Generated by Django 3.0.5 on 2020-04-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20200426_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specinfo',
            name='info',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
