# Generated by Django 3.0.5 on 2020-04-29 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_auto_20200429_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlifecycle',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items.Item'),
        ),
    ]
