# Generated by Django 3.0.5 on 2020-04-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_auto_20200429_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemlifecycle',
            old_name='assign_date_start',
            new_name='assigned_date',
        ),
        migrations.RemoveField(
            model_name='itemlifecycle',
            name='assign_confirm',
        ),
        migrations.RemoveField(
            model_name='itemlifecycle',
            name='assign_date_end',
        ),
        migrations.AddField(
            model_name='itemlifecycle',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
