# Generated by Django 3.0.5 on 2020-04-29 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_auto_20200429_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlifecycle',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item'),
        ),
    ]
