# Generated by Django 3.0.5 on 2020-04-30 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20200429_1721'),
        ('items', '0017_item_in_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemLifeCycle',
            new_name='ItemAssign',
        ),
    ]
