# Generated by Django 3.0.5 on 2020-05-03 09:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_auto_20200430_1829'),
        ('items', '0018_auto_20200430_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemassign',
            name='received_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='received_by', to='employees.Employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemassign',
            name='assign_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_by', to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='itemassign',
            name='assign_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_to', to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='itemassign',
            name='assigned_date',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[items.models.validate_future]),
        ),
        migrations.AlterField(
            model_name='itemassign',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True, validators=[items.models.validate_future]),
        ),
    ]
