# Generated by Django 3.0.5 on 2020-05-03 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_auto_20200430_1829'),
        ('items', '0019_auto_20200503_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemassign',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='received_by', to='employees.Employee'),
        ),
    ]
