# Generated by Django 3.0.5 on 2020-05-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_auto_20200503_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='lost_or_damaged',
            field=models.BooleanField(default=False),
        ),
    ]
