# Generated by Django 3.0.5 on 2020-05-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0022_item_lost_or_damaged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='lost_or_damaged',
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemassign',
            name='lost_or_damaged',
            field=models.BooleanField(default=False),
        ),
    ]
