# Generated by Django 3.0.5 on 2020-05-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0024_auto_20200503_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemassign',
            name='lost_or_damaged',
        ),
        migrations.AddField(
            model_name='itemassign',
            name='assign_status',
            field=models.CharField(choices=[(0, 'Assigned'), (1, 'Received'), (2, 'Expended'), (3, 'Lost'), (4, 'Damaged')], default=0, max_length=1),
        ),
    ]
