# Generated by Django 3.0.5 on 2020-05-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0027_auto_20200503_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='expendable',
            field=models.BooleanField(default=False),
        ),
    ]
