# Generated by Django 3.0.5 on 2020-05-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0029_remove_item_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='items',
            field=models.IntegerField(default=1),
        ),
    ]
