# Generated by Django 3.0.5 on 2020-05-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0032_model_item_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='model',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
