# Generated by Django 3.0.5 on 2020-05-05 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0033_auto_20200505_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='model',
            new_name='name',
        ),
    ]
