# Generated by Django 3.0.5 on 2020-05-07 13:29

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0034_auto_20200505_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.Manufacturer'),
        ),
        migrations.AlterField(
            model_name='model',
            name='category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='manufacturer', chained_model_field='manufacturers', on_delete=django.db.models.deletion.CASCADE, to='items.Category'),
        ),
        migrations.AlterField(
            model_name='model',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.Manufacturer'),
        ),
    ]
