# Generated by Django 3.0.5 on 2020-05-07 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_auto_20200503_2236'),
        ('items', '0035_auto_20200507_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=255)),
                ('mac', models.CharField(max_length=17)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
            ],
        ),
    ]
