# Generated by Django 3.0.5 on 2020-05-07 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_auto_20200503_2236'),
        ('items', '0036_personalitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonalItem',
            new_name='PersonalDevice',
        ),
    ]
