# Generated by Django 3.0.5 on 2020-05-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0037_auto_20200507_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldevice',
            name='device',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personaldevice',
            name='mac',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
    ]
